var canvas=document.createElement('canvas');var gl;var webGLdebugInfo;var webGLvendor;var webGLrenderer;try{gl=canvas.getContext('webgl')||canvas.getContext('experimental-webgl');}catch(e){}
if(gl){webGLdebugInfo=gl.getExtension('WEBGL_debug_renderer_info');webGLvendor=gl.getParameter(webGLdebugInfo.UNMASKED_VENDOR_WEBGL);webGLrenderer=gl.getParameter(webGLdebugInfo.UNMASKED_RENDERER_WEBGL);}
var PDTGUse3DStuff=false;function PDTGCanUse3DStuff(){if(gl){if(webGLrenderer.indexOf("SwiftShader")==-1){PDTGUse3DStuff=true;}}
return PDTGUse3DStuff;}
jQuery.browser={};jQuery.browser.msie=false;jQuery.browser.version=0;if(navigator.userAgent.match(/MSIE ([0-9]+)\./)){jQuery.browser.msie=true;jQuery.browser.version=RegExp.$1;}
var PDTGIsPrivateWindow=false;var checkCookieBannerIsHiddenInterval;jQuery(document).ready(function(){try{detectIncognito().then((result)=>{PDTGIsPrivateWindow=result.isPrivate;if(PDTGIsPrivateWindow==true){jQuery("body").addClass("ispriv");}});}catch(e){}
jQuery('#regular_portfolio').attr('id','full_width_portfolio');jQuery('#ftpfullpage').addClass('wpb_row vc_row-fluid vc_row full-width-content vc_row-o-equal-height vc_row-flex  vc_row-o-content-top');jQuery('.headerinnermenu .nav a').mouseover(function(event){});jQuery('.nav > ul > li > ul li.menu-item-has-children > a').append('<i class="fas fa-chevron-right"></i>');jQuery('.nav li.externallink > a').append('<i class="fas fa-external-link-alt"></i>');jQuery('.headerinnermenu .nav:not(.nav2) > ul > li.menu-item-has-children > a, .headerinnermenu .nav:not(.nav2) > ul > li > ul > li.menu-item-has-children > a').click(function(event){if(jQuery(window).width()<='1024'&&!jQuery(this).next('ul.sub-menu').hasClass('hovering')){event.preventDefault();jQuery('.headerinnermenu .nav ul.sub-menu').removeClass('hovering');jQuery(this).next('ul.sub-menu').addClass('hovering');}else{}});jQuery(document).scroll(function(){checkIfAtTopBGX();});checkIfAtTopBGX();jQuery('.navsearch form').attr('data-width',jQuery('.navsearch form').width());jQuery('.navsearch form').css('width','0px');if(jQuery('main').hasClass('adfullwidth')){jQuery('.wrapper').addClass('adfullwidth');}
jQuery("div.bb_h1").each(function(){jQuery(this).replaceWith('<h2>'+jQuery(this).html()+'</h2>');});jQuery("div.bb_h2").each(function(){jQuery(this).replaceWith('<h3>'+jQuery(this).html()+'</h3>');});jQuery("div.bb_h3").each(function(){jQuery(this).replaceWith('<h4>'+jQuery(this).html()+'</h4>');});jQuery('img.sharedFilePreviewYouTubeVideo').hide();jQuery.ajax({url:"/wp-content/themes/pd2tg/legacy/php/na-check.php",type:'GET',success:function(res){if(res=="US"){jQuery("body").addClass("visna");}else if(res=="ASIA"){jQuery("body").addClass("visasia");}else if(res=="JP"){jQuery("body").addClass("visjp");}else if(res=="KR"){jQuery("body").addClass("viskr");}else{jQuery("body").addClass("viseu");}}});jQuery(".guidecontainercontent h2, .guidecontainercontent h3, .guidecontainercontent h4, .guidecontainercontent h5, .guidecontainercontent h6").each(function(){jQuery(this).wrapInner('<span></span>');});jQuery(window).resize(function(){if(jQuery(window).width()<='1024'){jQuery('.frontpageslideshow').cycle('destroy');console.log('destroy fp cycle');}else{jQuery('.frontpageslideshow').cycle();console.log('create fp cycle');}});jQuery(window).resize();jQuery(".sharedFilePreviewYouTubeVideo").each(function(){var thisYTID=jQuery(this).attr('data-youtube');jQuery(this).replaceWith('<div class="adprodpagevideocontaineralt"><div class="adprodpagevideowrapper"><iframe    src="https://www.youtube.com/embed/'+thisYTID+'?autoplay=0&amp;modestbranding=1&amp;rel=0"  frameborder="0" width="1280" height="720" class="adprodpagevideoplayer"></iframe><div class="clear"></div>');});togglePD2DLCView('grid');jQuery('.navgameslink > a').click(function(){showHeaderGamesMenuNav();});jQuery('.hpgameoverlainner i.fa-times-circle').click(function(){hideHeaderGamesMenuNav();});jQuery.fn.isInViewportOmega=function(){var elementTop=jQuery(this).offset().top;var elementBottom=elementTop+jQuery(this).outerHeight();var viewportTop=jQuery(window).scrollTop();var viewportBottom=viewportTop+jQuery(window).height();return elementBottom>viewportTop&&elementTop<viewportBottom;};jQuery(window).scroll(function(){checkIfAutoPlayVideoIsInView();});checkIfAutoPlayVideoIsInView();jQuery('.addevdiaryvideoplayer').hide();jQuery('.addevdiaryvideoplayerinner, .addevdiaryvideoplayerinner i').mousedown(function(){hideADMDevDiaryVideo();});jQuery(".post-linkxd:not(a)").click(function(){window.location.href=jQuery(this).attr("data-linkxd");});if(jQuery("body").hasClass("pdlandscapelock")){try{screen.orientation.lock("landscape")}catch(error){console.error(error);}}
closePD2DLCPopUp();jQuery("div.dlclistxd:not(a)").click(function(){if(jQuery(this).data("paid")==true){showPD2DLCPopUp(jQuery(this).data("pid"));}else{window.location.href=jQuery(this).attr("data-linkxd");}});jQuery(".payday2dlclistpopupclose, .payday2dlclistpopupinnertopright i").click(function(){closePD2DLCPopUp();});jQuery(".headergetpayday a").click(function(){hidePDTGMenu();});jQuery(".pd2tgtimeconv").each(function(index){var DateTime=luxon.DateTime;DateTime.defaultZone="Europe/Stockholm";if(jQuery(this).data("datetime")){thisDate=DateTime.fromISO(jQuery(this).data("datetime"));jQuery(this).html(thisDate.toLocal().toLocaleString(DateTime.DATETIME_FULL));}else if(jQuery(this).data("date")){thisDate=DateTime.fromISO(jQuery(this).data("date"));jQuery(this).html(thisDate.toLocal().toLocaleString(DateTime.DATE_HUGE));}else if(jQuery(this).data("time")){thisDate=DateTime.fromISO(jQuery(this).data("time"));var newFormat={...DateTime.TIME_SIMPLE,timeZoneName:'short'};jQuery(this).html(thisDate.toLocal().toLocaleString(newFormat));}else{}});if(jQuery(".wpml-ls-sub-menu").children().length<=0){jQuery(".navlang").remove();}
jQuery(".pdtgfooternewsletterclose span").click(function(){pdtgCloseNewsletterBanner()});jQuery(".headerbigbanner a, .headerbigbanner i").click(function(){pdtgCloseHeaderBanner()});jQuery(".pdtgfooternewsletter").hide();if(Cookies.get('pdtgHideHeaderBanner')=="true"){jQuery(".headerbigbanner").hide();}
checkABBtnInt=setInterval(function(){if(jQuery(".ab-wpr-login-button").length>0){jQuery(".ab-wpr-login-button").wrapInner("<span></span>");clearInterval(checkABBtnInt);}
if(jQuery(".ab-wpr-user-profile-button").length>0){clearInterval(checkABBtnInt);}},1000);});function showADMDevDiaryVideo(youtubeid="unset"){if(youtubeid=="unset"){return true;}else{jQuery('.addevdiaryvideoplayer').show();jQuery('#addevdiaryvideoplayerplayer').attr('src','https://www.youtube.com/embed/'+youtubeid+'?rel=0&amp;showinfo=0&amp;autoplay=1');return false;}}
function hideADMDevDiaryVideo(){jQuery('.addevdiaryvideoplayer').hide();jQuery('#addevdiaryvideoplayerplayer').attr('src','/ts.htm');}
function checkIfAutoPlayVideoIsInView(){if(jQuery('video.autoplayvideoonviewport').length>0){jQuery('video.autoplayvideoonviewport').each(function(){if(jQuery(this).isInViewportOmega()){if(!jQuery(this).hasClass('autoplayvideostarted')){jQuery(this).addClass('autoplayvideostarted');jQuery(this).trigger('load');jQuery(this).trigger('play');}else{}}});}}
function checkIfProductBoxImageIsInView(){}
function togglePDTGMenu(){if(jQuery('.headerinnermenu').hasClass('active')){hidePDTGMenu();}else{showPDTGMenu();}}
function showPDTGMenu(){jQuery('.headerinnermenu').addClass('active');jQuery('.header .fa-bars').fadeOut();}
function hidePDTGMenu(){jQuery('.headerinnermenu').removeClass('active');jQuery('.header .fa-bars').fadeIn();}
function togglePD2DLCList(slugx="all"){var currentSlug=jQuery('body').attr('data-dlcslug');if(currentSlug==slugx){}else{jQuery('.payday2dlclistinnerbox, .payday2dlclistinneraltrow').fadeOut(300);setTimeout(function(){if(slugx=="all"){jQuery('.payday2dlclistinnerbox, .payday2dlclistinneraltrow').fadeIn(300);}else{jQuery('.payday2dlclistinnerbox, .payday2dlclistinneraltrow').each(function(){thisBoxSlug=jQuery(this).attr('data-terms');if(thisBoxSlug.indexOf(slugx)!=-1){jQuery(this).fadeIn(300)}});}},250);}
jQuery('.payday2dlclisttopinnerr a').removeClass('active');jQuery('.payday2dlclisttopinnerr a[data-slug="'+slugx+'"]').addClass('active');jQuery('body').attr('data-dlcslug',slugx);}
function togglePD2DLCView(typex='grid'){if(typex=='grid'){jQuery('.payday2dlclistinneralt').hide();jQuery('.payday2dlclistinner').show();jQuery('.payday2dlclisttopinnerl a').removeClass('active');jQuery('.payday2dlclisttopinnerl a.grid').addClass('active');}
if(typex=='list'){jQuery('.payday2dlclistinner').hide();jQuery('.payday2dlclistinneralt').show();jQuery('.payday2dlclisttopinnerl a').removeClass('active');jQuery('.payday2dlclisttopinnerl a.list').addClass('active');}}
function closePD2DLCPopUp(){jQuery(".payday2dlclistpopup").hide();}
function showPD2DLCPopUp(dlcpid){if(typeof dlcpid!=='undefined'){var thisDLCpid=jQuery(".payday2dlclistinneraltrow[data-pid='"+dlcpid+"']");jQuery(".payday2dlclistpopupname").text(thisDLCpid.find("h3").text());jQuery(".payday2dlclistpopupdesc").text(thisDLCpid.find(".payday2dlcdesc").text());jQuery(".payday2dlclistpopupimg").attr("src",thisDLCpid.find("img").attr("src"));jQuery(".adplatformbtnnewweb").attr("href",thisDLCpid.data("linkxd"));if(thisDLCpid.data("steam")){jQuery(".payday2dlclistpopup .adplatformbtnnews1").attr("href",thisDLCpid.data("steam"));jQuery(".payday2dlclistpopup .adplatformbtnnews1").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnews1").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnews1").hide();}
if(thisDLCpid.data("eg")){jQuery(".payday2dlclistpopup .adplatformbtnnewegs").attr("href",thisDLCpid.data("eg"));jQuery(".payday2dlclistpopup .adplatformbtnnewegs").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnewegs").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnewegs").hide();}
if(thisDLCpid.data("xsx")){jQuery(".payday2dlclistpopup .adplatformbtnnewxbxsx").attr("href",thisDLCpid.data("xsx"));jQuery(".payday2dlclistpopup .adplatformbtnnewxbxsx").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnewxbxsx").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnewxbxsx").hide();}
if(thisDLCpid.data("ps5eu")||thisDLCpid.data("ps5na")||thisDLCpid.data("ps5jp")||thisDLCpid.data("ps5asia")){if(jQuery("body").hasClass("visna")){jQuery(".payday2dlclistpopup .adplatformbtnnewps5").attr("href",thisDLCpid.data("ps5na"));}else if(jQuery("body").hasClass("visjp")){jQuery(".payday2dlclistpopup .adplatformbtnnewps5").attr("href",thisDLCpid.data("ps5jp"));}else if(jQuery("body").hasClass("visasia")){jQuery(".payday2dlclistpopup .adplatformbtnnewps5").attr("href",thisDLCpid.data("ps5asia"));}else{jQuery(".payday2dlclistpopup .adplatformbtnnewps5").attr("href",thisDLCpid.data("ps5eu"));}
jQuery(".payday2dlclistpopup .adplatformbtnnewps5").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnewps5").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnewps5").hide();}
if(thisDLCpid.data("x1")){jQuery(".payday2dlclistpopup .adplatformbtnnewxb1").attr("href",thisDLCpid.data("x1"));jQuery(".payday2dlclistpopup .adplatformbtnnewxb1").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnewxb1").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnewxb1").hide();}
if(thisDLCpid.data("x360")){jQuery(".payday2dlclistpopup .adplatformbtnnewxb360").attr("href",thisDLCpid.data("x360"));jQuery(".payday2dlclistpopup .adplatformbtnnewxb360").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnewxb360").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnewxb360").hide();}
if(thisDLCpid.data("ps4eu")||thisDLCpid.data("ps4na")){if(jQuery("body").hasClass("visna")){jQuery(".payday2dlclistpopup .adplatformbtnnewps1").attr("href",thisDLCpid.data("ps4na"));}else{jQuery(".payday2dlclistpopup .adplatformbtnnewps1").attr("href",thisDLCpid.data("ps4eu"));}
jQuery(".payday2dlclistpopup .adplatformbtnnewps1").show();}else{jQuery(".payday2dlclistpopup .adplatformbtnnewps1").attr("href","#");jQuery(".payday2dlclistpopup .adplatformbtnnewps1").hide();}}
jQuery(".payday2dlclistpopup").show();setTimeout(function(){jQuery(".payday2dlclistpopup").scrollTop(0);},25);}
function showHeaderGamesMenuNav(){jQuery('.hpgameoverlay').addClass('active');jQuery('.hpgameoverlay').removeClass('zoom');}
function hideHeaderGamesMenuNav(){jQuery('.hpgameoverlay').addClass('zoom');setTimeout(function(){jQuery('.hpgameoverlay').removeClass('active');},750);}
function checkIfAtTopBGX(){if(jQuery(window).scrollTop()===0){jQuery(".header").removeClass('bgx');jQuery(".productnav").removeClass('bgx');}else{jQuery(".header").addClass('bgx');jQuery(".productnav").addClass('bgx');}}
function showPDTGSearchWindow(){jQuery('#navsearchtoggle, .search-submit').hide();jQuery(".navsearch form").animate({width:(parseInt(jQuery(".navsearch form").attr('data-width'))+100),});jQuery(".nav.nav2").animate({'padding-right':80,});jQuery('.navsearch form input.search-input').focus();setTimeout(function(){jQuery('.search-submit').show();},400);}
function hidePDTGSearchWindow(){jQuery('.search-submit').hide();jQuery(".navsearch form").animate({width:0,},{complete:function(){jQuery('#navsearchtoggle').show();}});jQuery(".nav.nav2").animate({'padding-right':0,});}
function checkPDTGSearchFormIfEmpty(){if(!jQuery('.navsearch form input.search-input').val()){hidePDTGSearchWindow();return false;}else{return true;}}
function addBodyNoScroll(){jQuery("html").addClass("noscroll");}
function removeBodyNoScroll(){jQuery("html").removeClass("noscroll");}
function pdtgCheckToShowNewsletterBanner(){if(jQuery(".cookie-notice").is(":visible")==false&&Cookies.get('pdtgHideNewsletterBanner')==undefined){try{jQuery.ajax({url:"https://nebula.starbreeze.com/agreement/public/agreements/policies",type:'GET',crossDomain:true,xhrFields:{withCredentials:true},success:function(data,textStatus,jqXHR){for(thisData of data){if(thisData["policyId"]=="86b9444a-2b1c-440a-a8e9-a262fca5fa41"){if(thisData["isAccepted"]==false){jQuery(".pdtgfooternewsletter").fadeIn();jQuery("footer.footer").append('<img src="https://t.paydaythegame.com/imgp/z0a7og" alt="" />');}else{jQuery(".pdtgfooternewsletter").fadeOut();}}}
clearInterval(checkCookieBannerIsHiddenInterval);},error:function(jqXHR,textStatus,errorThrown){jQuery(".pdtgfooternewsletter").fadeIn();jQuery("footer.footer").append('<img src="https://t.paydaythegame.com/imgp/z0a7og" alt="" />');},complete:function(jqXHR,textStatus){clearInterval(checkCookieBannerIsHiddenInterval);}});}catch(err){}}else{jQuery(".pdtgfooternewsletter").fadeOut();}}
function pdtgCloseNewsletterBanner(){jQuery(".pdtgfooternewsletter").fadeOut();Cookies.set('pdtgHideNewsletterBanner','true',{expires:60});console.log("Hide Newsletter Banner");}
function pdtgCloseHeaderBanner(){jQuery(".headerbigbanner").fadeOut();Cookies.set('pdtgHideHeaderBanner','true',{expires:60});console.log("Hide Header Banner");}