jQuery(document).ready(function(){if(jQuery(".supportsection").length>0){doStartHash();jQuery(window).on('hashchange',function(e){doStartHash();});setTimeout(function(){jQuery('html,body').scrollTop(0);},75);}
closeAllQuestions();jQuery('.supportquestionboxq').not('.supportquestionboxqstatic').click(function(evt){var thisThing=jQuery(this).parent();if(!jQuery(this).parent().hasClass('active')){setTimeout(function(){thisThing.addClass('active');thisThing.children(".supportquestionboxa").not(".supportquestionboxastatic").slideDown();if(thisThing.children(".supportquestionboxq").children("i").hasClass("fa-chevron-down")){thisThing.children(".supportquestionboxq").children("i").removeClass("fa-chevron-down").addClass("fa-chevron-up");}},50);}else{setTimeout(function(){thisThing.removeClass('active');thisThing.children(".supportquestionboxa").not(".supportquestionboxastatic").slideUp();console.log(thisThing.children(".supportquestionboxq").children("i").attr("class"));if(thisThing.children(".supportquestionboxq").children("i").hasClass("fa-chevron-up")){thisThing.children(".supportquestionboxq").children("i").removeClass("fa-chevron-up").addClass("fa-chevron-down");}},50);}});if(jQuery(".pdbreakingissuecont").length>0){closeAllBreakingIssues();}
jQuery('.pdbreakingissueboxcollapsable').not('.pdbreakingissueboxdesc').click(function(evt){if(!jQuery(this).hasClass('active')){var thisThing=jQuery(this);closeAllBreakingIssues();setTimeout(function(){thisThing.addClass('active');thisThing.find(".pdbreakingissueboxdesc").slideDown();thisThing.find('.pdbreakingissueboxtitle i').removeClass("fa-chevron-down").addClass("fa-chevron-up");},50);}else{closeAllBreakingIssues();}});});jQuery('.supportsection, #backtostart').hide();function doStartHash(){var startHash=window.location.hash.substr(1);if(startHash==""||startHash=="!"){startHash="start";}
if(startHash=="payday2-steam"||startHash=="payday2-epic"){startHash="payday2-pc";window.location.hash="#payday2-pc";}
if(startHash!=""){changeSupportPage(startHash);}}
function changeSupportPage(pageName){if(pageName!=""){console.log('change page to: '+pageName);jQuery('.supportsection').fadeOut(200).promise().done(function(){jQuery('div[id="'+pageName+'"]').fadeIn(200);});if(pageName=="start"){jQuery('#backtostart').fadeOut(200);setTimeout(function(){jQuery('html,body').scrollTop(0);},50);}else{jQuery('#backtostart').fadeIn(200);}
if(pageName=="payday2-pc"||pageName=="payday2-console"){setTimeout(function(){jQuery('#payday2-extra').fadeIn(500);},500);}else{jQuery('#payday2-extra').fadeOut(200);}
return false;}}
function closeAllQuestions(){jQuery('.supportquestionboxa').not('.supportquestionboxastatic').slideUp();setTimeout(function(){jQuery('.supportquestionbox').not('.supportquestionboxstatic').removeClass('active');jQuery(".supportquestionboxq i").each(function(){if(jQuery(this).hasClass("fa-chevron-up")){jQuery(this).removeClass("fa-chevron-up").addClass("fa-chevron-down")}});},50);}
function expandAllQuestions(){jQuery('.supportquestionboxa').not('.supportquestionboxastatic').slideDown();setTimeout(function(){jQuery('.supportquestionbox').not('.supportquestionboxstatic').addClass('active');jQuery(".supportquestionboxq i").each(function(){if(jQuery(this).hasClass("fa-chevron-down")){jQuery(this).removeClass("fa-chevron-down").addClass("fa-chevron-up")}});},50);}
function closeAllBreakingIssues(){jQuery('.pdbreakingissueboxcollapsable .pdbreakingissueboxdesc').slideUp();jQuery('.pdbreakingissueboxcollapsable .pdbreakingissueboxtitle i').removeClass("fa-chevron-up").addClass("fa-chevron-down");setTimeout(function(){jQuery('.pdbreakingissueboxcollapsable').removeClass('active');},50);}